app_react:
    path: /{reactRouting}
    controller: App\Controller\DefaultController::index
    requirements:
        reactRouting: .*

login:
    path: /api/auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]