
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    carousel_directory: '%kernel.project_dir%/public/uploads/images/carousel'
    zoo_email: '%env(zooarcadia930@gmail.com)%'
services:
    
    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            $passwordHasher: '@security.password_hasher'
    

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailerService:
        arguments:
            $zooEmail: '%zoo_email%'
        autowire: true
        autoconfigure: true

    App\Controller\ContactController:
        arguments:
            $mailer: '@App\Service\MailerService'

    App\Controller\AdminController:
        arguments:
            $mailer: '@App\Service\MailerService'
    App\Service\UserService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@security.password_hasher'

