nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization','Accept']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        # expose_headers: ['Link']
        max_age: 3600
        allow_credentials: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization','Accept']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: false